In [2]:
import numpy as np
import numpy.random as random
import matplotlib.pyplot as plt

# NumPy Random numbers

Random numbers are extremely useful for statisitc analysis.\
It could be used for numiercal calculations as well (so called the Monte Carlo methods).

However, generating random numbers with a computer is not esay.\
It rquires a random number generator.

Python has a build-in random number generator that can be used by `import random`.

In practice, NEVER use the default random number generator for scientidical calculations.\
The rule is applied to most programming language.

In [3]:
# don't use the default random number generator for scientifical calculations.
#
#import random  

`numpy` has a much better random number generator.\
 It can be imported by `import numpy.random as random`.

 All random number generators requrie a "seed" to initialize the generator.\
 The default seed is usually taken from some time-dependent variable.\
 Thus, everytime you call the generator, it will give you a different random number.

 When developing or debuggin the code, you want to keep the same seed to reproduce the same results.
 We could specify the seed by: 

In [4]:
random.seed(seed=123) # optional; used if you want to reproduce the results

This is a convenience, legacy function that exists to support older code.

The new way to set the random number seed is to use the `Generator` instance. 

In [5]:
rng = random.default_rng(seed=12345) # set the seed
print(rng) # a random number generator

Generator(PCG64)


In [6]:
print(random.random())
print(random.random())

0.6964691855978616
0.28613933495037946


In [7]:
# Generator 10 random integers from 0 to 100

# old way
random.randint(low=0, high=100, size=10)

# new way
rng.integers(low=0, high=100, size=10)

array([69, 22, 78, 31, 20, 79, 64, 67, 98, 39])

In [8]:
# Generate 10 random floats from 0 to 1.

# old way
random.rand(10)

# new way
print(rng.random(10))
print(rng.random(1))
print(rng.random())

[0.33281393 0.59830875 0.18673419 0.67275604 0.94180287 0.24824571
 0.94888115 0.66723745 0.09589794 0.44183967]
[0.88647992]
0.6974534998820221


In [9]:
# Generate 5x5 random floats from 0 to 1

# old way
random.rand(5,5)

# new way
rng.random((5,5))

array([[0.32647286, 0.73392816, 0.22013496, 0.08159457, 0.1598956 ],
       [0.34010018, 0.46519315, 0.26642103, 0.8157764 , 0.19329439],
       [0.12946908, 0.09166475, 0.59856801, 0.8547419 , 0.60162124],
       [0.93198836, 0.72478136, 0.86055132, 0.9293378 , 0.54618601],
       [0.93767296, 0.49498794, 0.27377318, 0.45177871, 0.66503892]])

### Exercise 1: Random numbers

1. Generate 10 random numbers from -1 to 1. [float]
2. Generate 10 random numbers from 0 to 100. [float]

In [10]:
# TODO:

data1 = 2*rng.random(10) - 1
data2 = 100*rng.random(10)

print(data1)
print(data2)


[-0.33821814  0.80690801 -0.48585165 -0.32034332 -0.4822932  -0.28910704
 -0.98995533  0.25720909 -0.43523459 -0.86382462]
[61.68289773 17.63263203 30.43883872 44.08868109 15.02023411 21.79288631
 47.43331153 47.63688551 25.52323538 29.75652681]


### Generate random samples from a given array

Instead of generate random integers/numbers, we want to randomly generate samples from a given array.

For example, a poker deck 13x4 cards. 

In [11]:
# Poker
ranks = ["2","3","4","5","6","7","8","9","10","J","Q","K"]
suits = ["S","D","H","C"]

In [12]:
# Randomly pickup a rank from ranks

# old way
random.choice(ranks, size=1)

# new way
rng.choice(ranks, size=5)

array(['K', '5', '10', '5', 'Q'], dtype='<U2')

we could assign a given probability function a well.

In [13]:
# Randomly pickup 10 numbers from a list=[1,2,3,4,5] with a probability function 'p'

# old way
random.choice([1,2,3,4,5], p = [0.8, 0.05, 0.05, 0.05, 0.05], size= 10)

# new way
rng.choice([1,2,3,4,5],p=[0.8, 0.05, 0.05, 0.05, 0.05], size=10)

array([1, 1, 1, 2, 1, 3, 1, 1, 1, 1])

### Shuffing an array (list)

In [14]:
students = ["Einstein", "Newton", "Maxwell"]

# old way
random.shuffle(students)
print(students)

# new way
rng.shuffle(students)

for s in students:
  print(s)

['Maxwell', 'Newton', 'Einstein']
Einstein
Newton
Maxwell


## Exercise 2: A Gacha Game (轉蛋)

Write a very simple Gacha game.

1. Write a python class named "Gacha".
2. The class has three attibutes, which are numpy arrys. Each array host the character polls with different ranks.
3. There are three ranks in this Gacha game: super rare (SR), super-super rare (SSR), and ultra rate (UR). 
4. The probabilities to draw each rank are: SR: 87%, SSR: 10%, and UR: 3% 
5. Use the character polls I provided below. 
5. Write a class instance called "draw()". It will return tuple contains rank and a character with that rank.

In [15]:
from dataclasses import dataclass

@dataclass
class Character:
    def __init__(self,name, rank, skills=None):
        self.name  = name
        self.skill = skills
        if rank.upper() in ("SR","SSR", "UR"):
            self.rank = rank.upper()
        else:
            raise ValueError(f"Unspport rank {rank}")
        return

In [16]:
ur_physicists = [
    "Albert Einstein",
    "Isaac Newton",
    "Richard Feynman",
    "Stephen Hawking",
    "Niels Bohr",
    "Max Planck",
    "Erwin Schrödinger",
    "Werner Heisenberg",
    "Galileo Galilei",
    "Marie Curie"
]

ssr_physicists = [
    "James Clerk Maxwell",
    "Michael Faraday",
    "Enrico Fermi",
    "Ernest Rutherford",
    "Paul Dirac",
    "Wolfgang Pauli",
    "Carl Sagan",
    "Brian Greene",
    "Lisa Randall",
    "Neil deGrasse Tyson"
]

sr_physicists = [
    "Albert Michelson",
    "Christiaan Huygens",
    "Hermann Minkowski",
    "J. Robert Oppenheimer",
    "Lise Meitner",
    "Robert Boyle",
    "Sally Ride",
    "Srinivasa Ramanujan",
    "Subrahmanyan Chandrasekhar",
    "William Thomson (Lord Kelvin)"
]

In [17]:
chars_sr  = [Character(name=name,rank="sr")  for name in sr_physicists]
chars_ssr = [Character(name=name,rank="ssr") for name in ssr_physicists]
chars_ur  = [Character(name=name,rank="ur")  for name in ur_physicists]

In [18]:
class Gacha:
    def __init__(self, chars_sr, chars_ssr, chars_ur) -> None:
        self.chars_sr = chars_sr
        self.chars_ssr = chars_ssr
        self.chars_ur = chars_ur
        self.rng = random.default_rng()

    def draw(self, size):
        self.size = size
        chars = self.chars_sr + self.chars_ssr + self.chars_ur
        prob_sr  = np.ones(len(self.chars_sr))*0.87
        prob_ssr = np.ones(len(self.chars_ssr))*0.1
        prob_ur  = np.ones(len(self.chars_ur))*0.03
        prob = np.concatenate((prob_sr, prob_ssr, prob_ur))
        prob_norm = prob/np.sum(prob)
        char_draw = self.rng.choice(chars, p=prob_norm, size=size)
        return char_draw

In [19]:
N = 10
g = Gacha(chars_sr, chars_ssr, chars_ur)
g_class = g.draw(N)
for i in g_class:
  print(f'({i.rank:3}) {i.name}')

(SR ) Robert Boyle
(SR ) Albert Michelson
(SR ) Srinivasa Ramanujan
(SR ) Srinivasa Ramanujan
(SR ) Lise Meitner
(SR ) J. Robert Oppenheimer
(SR ) Lise Meitner
(SR ) Albert Michelson
(SR ) Robert Boyle
(SR ) J. Robert Oppenheimer


### continues

7. draw 100 times, measure how many UR did you get? and how many `Albert Einstein` did you get?
8. Now assuming that there is a "Albert Einstein" pickup poll. Keep the same 3% probability for UR characters, but raise the probability to draw Einstein to 0.75% and make other UR characters have a uniform probability function.
9. If you need 5 copies of Albert Einstein, measure how many draws do you need?
10. If 30 draws cost 2000 NTD, how much money you spent to get 5 Albert Einstein? (note that different people has different answer. You could measure that you are 歐洲人 or 非洲人)


In [20]:
class Gacha:
    def __init__(self, chars_sr, chars_ssr, chars_ur) -> None:
        self.chars_sr = chars_sr
        self.chars_ssr = chars_ssr
        self.chars_ur = chars_ur
        self.rng = random.default_rng()
        self.counter = 0
        self.counter_sr = 0
        self.counter_ssr = 0
        self.counter_ur = 0
        self.albert = 0

    def draw(self, size,):
        self.size = size
        chars = self.chars_sr + self.chars_ssr + self.chars_ur
        prob_sr  = np.ones(len(self.chars_sr))*0.87
        prob_ssr = np.ones(len(self.chars_ssr))*0.1
        prob_ur  = np.ones(len(self.chars_ur))*0.03
        prob = np.concatenate((prob_sr, prob_ssr, prob_ur))
        prob_norm = prob/np.sum(prob)
        char_draw = self.rng.choice(chars, p=prob_norm, size=size)
        for i in char_draw:
            if self.albert > 4:
                break
            self.counter += 1
            if i.rank == "UR":
                self.counter_ur += 1
            if i.rank == "SSR":
                self.counter_ssr += 1
            if i.rank == "SR":
                self.counter_sr += 1
            if i.name == "Albert Einstein":
                self.albert += 1
        
        # Show statistics
        print(f'Albert Einstein: {self.albert} times')
        print(f'Total: {self.counter}')
        print(f'SR : {self.counter_sr:<4} times, prob = {(self.counter_sr/self.counter)*100:<6.3f}%')
        print(f'SSR: {self.counter_ssr:<4} times, prob = {(self.counter_ssr/self.counter)*100:<6.3f}%')
        print(f'UR : {self.counter_ur:<4} times, prob = {(self.counter_ur/self.counter)*100:<6.3f}%')
        return 

In [21]:
N = int(1e4)
g_albert = Gacha(chars_sr, chars_ssr, chars_ur)
g_class = g_albert.draw(N)

Albert Einstein: 5 times
Total: 2879
SR : 2541 times, prob = 88.260%
SSR: 270  times, prob = 9.378 %
UR : 68   times, prob = 2.362 %


Take home message: Gacha games are evil. 

### Exercuse 3: Monte Carllo method for numerical integration.

```
    +----------------------------------------+   
    1 |          ..--/"""""|""""\--._          | y1
      |      .r*"`         |         "*..      | y2
      |    ./'             |            '\.    |   
      |  _/                |               \,  |   
      | /                  |                "\ |   
      |.`                  |                  .|   
      |,                   |                  ,|   
      |r-------------------r-------------------|   
      |.                   |                  .|   
      |\.                  |                  ,|   
      | \                  |                ./ |   
      |  ".                |               ./  |   
      |   "\..             |            ../`   |   
      |      "*._.         |         _r*'      |   
   -1 |          '\--._____L____.--/"          |   
      +----------------------------------------+   
       -1                                     1  
```

We know that the area of a unit circle is PI.\
A cicumscribing square has an area 2x2 =4.\

We randomly throw `N` darts in the is square, we can count how many darts are within the circle (called it `M`).
The ratio of darts within the circle to the total number of darts (N) should represent the area ratio of circle to the squre.
Therefore, M/N = pi/4, gives pi = (4 * M/N).




1. Use the Monte Carlo method we described above to calculate PI with N= 10_000.
2. Check the convergence by increasing the number of N. Did it converge? How fast is the converging rate?

In [29]:
# TODO

N = int(1e4)
x = 2*rng.random(N) - 1
y = 2*rng.random(N) - 1
inside = 0
tot = 0

dis = np.sqrt(np.square(x) + np.square(y))
for i in dis:
  if i <= 1:
    inside += 1
  tot += 1

area = 4*inside/tot
print(area)

3.1232
